### ISSUE TITLE
Evil Devices

### ISSUE THREAD

**Issue by Blaisinchaze** [Blaisinchaze/GGJ2022#7]
Evil devices need the states, "following player", "Out of battery/Charging", "Overcharged", "Dead"
Evil enemies faces need to point towards the enemies target and change based on state
Deal damage to the player with a cooldown 
When transitioning to the dead state the enemy needs to explode and change sprite to the broken battery

**Comment by QuinnBug** [comment]
Need an animation/particle for the overcharge state
I think everything else is done, overcharge duration might need testing
