### ISSUE TITLE
Waves/Spawning enemies

### ISSUE THREAD

**Issue by Blaisinchaze** [Blaisinchaze/GGJ2022#8]
The game is split into waves that increase and are ultimately the players' score
Once every enemy has been destroyed, the next wave will start
When a wave starts, it will spawn a set number of enemies that increase with every wave
Spawn points will be linked to unlocked rooms, once a room is unlocked the spawners become active

**Comment by QuinnBug** [comment]
This is done, currently linked to time (can be switched)

There's multiple variables to tweak for funsies
